name: terraform-cloud-init

on: [repository_dispatch]

jobs:
  deploy-oci-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Initialize Workspace
        if: contains(github.event.action,'runner')
        env:
          TRIGGER: ${{ github.event.client_payload.repository }}
        run: |
          export TF_WORKSPACE=$(echo $TRIGGER | cut -d "/" -f 2)
          export TF_CLOUD_ORGANIZATION=${{ github.repository_owner }}
          terraform init -upgrade
