name: terraform-cloud-init

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout master
#        uses: actions/checkout@v2
#        with:
#          submodules: true
      - name: Terraform Cloud Workspace
        run: |
          curl -X POST https://api.github.com/repos/dashaun/terraform-cloud/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "init '"$GITHUB_REPOSITORY"'", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'