name: validate-plan-apply-destroy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Cloud Workspace Init
        run: |
          curl -X POST https://api.github.com/repos/dashaun/terraform-cloud/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "init '"$GITHUB_REPOSITORY"'", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
          export TF_WORKSPACE=dynamic-tf-oci-arm64-runner
          export TF_CLOUD_ORGANIZATION=dashaun
          export TF_VAR_github_user=dashaun
          export TF_VAR_oci_compartment_id=${{ secrets.OCI_COMPARTMENT_ID }}
          export TF_VAR_tailscale_auth_key=${{ secrets.TAILSCALE_AUTH_TOKEN }}

      - name: Checkout master
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: terraform init
        run: terraform init

      - name: terraform validate
        id: validate
        run: terraform validate -no-color

      - name: terraform plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: terraform apply
        id: apply
        if: steps.plan.outcome == 'success'
        run: terraform apply -auto-approve

      - name: terraform destroy
        id: destroy
        if: steps.plan.apply == 'success'
        run: terraform destroy -auto-approve